### ISSUE TITLE
Cannot retrain ml-QM-GNN

### ISSUE THREAD

**Issue by kntkb** [coleygroup/QM-augmented_GNN#3]
Hi! 

Thank you for sharing this interesting repo. I am trying to reproduce some the experiments but I encounter the following error when I try to retrain the ml-QM-GNN model. I would appreciate if some one can help me out what the problem is.

Best regards,
Ken

**Code**
>python reactivity.py -m ml_QM_GNN --data_path datasets/e2_sn2_regression.csv --model_dir trained_model/GNN_e2_sn2

**Error**
```
~/data/qm-augmented-gnn-test/QM-augmented_GNN/regression_e2_sn2/reactivity.py:103: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  hist = model.fit_generator(
Traceback (most recent call last):
  File "~/data/qm-augmented-gnn-test/QM-augmented_GNN/regression_e2_sn2/reactivity.py", line 103, in <module>
    hist = model.fit_generator(
  File "~/mambaforge/envs/chemprop-cpu/lib/python3.10/site-packages/keras/engine/training.py", line 2604, in fit_generator
    return self.fit(
  File "~/mambaforge/envs/chemprop-cpu/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "~/mambaforge/envs/chemprop-cpu/lib/python3.10/site-packages/tensorflow/python/eager/execute.py", line 52, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:

Detected at node 'gradient_tape/wln_regressor/ConcatOffset' defined at (most recent call last):
    File "~/data/qm-augmented-gnn-test/QM-augmented_GNN/regression_e2_sn2/reactivity.py", line 103, in <module>
      hist = model.fit_generator(
    File "~/mambaforge/envs/chemprop-cpu/lib/python3.10/site-packages/keras/engine/training.py", line 2604, in fit_generator
      return self.fit(
    File "~/mambaforge/envs/chemprop-cpu/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "~/mambaforge/envs/chemprop-cpu/lib/python3.10/site-packages/keras/engine/training.py", line 1650, in fit
      tmp_logs = self.train_function(iterator)
    File "~/mambaforge/envs/chemprop-cpu/lib/python3.10/site-packages/keras/engine/training.py", line 1249, in train_function
      return step_function(self, iterator)
    File "~/mambaforge/envs/chemprop-cpu/lib/python3.10/site-packages/keras/engine/training.py", line 1233, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "~/mambaforge/envs/chemprop-cpu/lib/python3.10/site-packages/keras/engine/training.py", line 1222, in run_step
      outputs = model.train_step(data)
    File "~/mambaforge/envs/chemprop-cpu/lib/python3.10/site-packages/keras/engine/training.py", line 1027, in train_step
      self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "~/mambaforge/envs/chemprop-cpu/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 526, in minimize
      grads_and_vars = self.compute_gradients(loss, var_list, tape)
    File "~/mambaforge/envs/chemprop-cpu/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 259, in compute_gradients
      grads = tape.gradient(loss, var_list)
Node: 'gradient_tape/wln_regressor/ConcatOffset'
All dimensions except 0 must match. Input 1 has shape [10 12 200] and doesn't match input 0 with shape [10 12 50].
         [[{{node gradient_tape/wln_regressor/ConcatOffset}}]] [Op:__inference_train_function_5412]
2023-01-25 14:07:32.365054: W tensorflow/core/kernels/data/generator_dataset_op.cc:108] Error occurred when finalizing GeneratorDataset iterator: FAILED_PRECONDITION: Python interpreter state is not initialized. The process may be terminated.
         [[{{node PyFunc}}]]
```

**Environment**
[myenv.yml.txt](https://github.com/coleygroup/QM-augmented_GNN/files/10503032/myenv.yml.txt)

**Comment by tstuyver** [comment]
Hi, 

Thanks for bringing this up! I just updated a couple of lines which should resolve this issue (see the latest push). If the problem persists (or another comes up), please let me know.

Kind regards,
Thijs

**Comment by kntkb** [comment]
@tstuyver Thank you for your time. The problem is solved and now I could retrain the model!
